# Generated by Django 3.1.2 on 2021-01-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0003_auto_20210114_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='image_upload',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
