# Generated by Django 3.1.2 on 2021-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0004_auto_20210114_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='description',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
    ]
