# Generated by Django 3.1.2 on 2021-01-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0007_auto_20210117_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='post.html', max_length=50),
        ),
    ]
