# Generated by Django 3.1.2 on 2021-01-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0008_post_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='template',
            field=models.CharField(default='post.html', max_length=50),
        ),
    ]
