# Generated by Django 3.1.2 on 2021-01-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0011_auto_20210118_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_upload',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_to',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='template',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
