# Generated by Django 3.1.2 on 2021-01-18 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0012_auto_20210118_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=models.CharField(max_length=50)),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=models.CharField(max_length=50), max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(default='none', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='link_to',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.CharField(default='post.html', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
