# Generated by Django 3.1.2 on 2021-01-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0013_auto_20210118_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='description',
            field=models.CharField(default=models.CharField(default='A new archive', max_length=50), max_length=100),
        ),
        migrations.AlterField(
            model_name='archives',
            name='title',
            field=models.CharField(default='A new archive', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default=models.CharField(default='A new post', max_length=50), max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='A new post', max_length=50),
        ),
    ]
