# Generated by Django 3.1.2 on 2021-01-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nw_site', '0002_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='link_to',
            field=models.CharField(default='/archives', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='link_to',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
