apiVersion: apps/v1
kind: Deployment
metadata:
  name: novvsworld
  namespace: novvsworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novvsworld
  template:
    metadata:
      labels:
        app: novvsworld
    spec:
      containers:
        - name: novvsworld
          image: registry.digitalocean.com/eo-registry/novvsworld:latest
          volumeMounts:
          - name: db-cert
            mountPath: "etc/certs"
            readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: novvworld-secrets
                  key: DBHOST
            - name: DBPORT
              value: "25060"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: novvworld-secrets
                  key: DBUSER
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: novvworld-secrets
                  key: DBPASS
            - name: DBSSLMODE
              valueFrom:
                secretKeyRef:
                  name: novvworld-secrets
                  key: DBSSLMODE
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: novvworld-secrets
                  key: SENDGRID_API_KEY
            - name: CA_CERT
              valueFrom:
                secretKeyRef:
                  name: novvworld-secrets
                  key: CA_CERT
      volumes:
      - name: db-cert
        secret:
          secretName: db-ca-cert

---
kind: Service
apiVersion: v1
metadata:
  name: novvsworld-service
  namespace: novvsworld
spec:
  selector:
    app: novvsworld
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-novvsworld
  namespace: novvsworld
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - novvs.world
    - secretName: novvsworld-tls-certs
  rules:
    - host: novvs.world
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novvsworld-service
                port:
                  number: 3000